### ISSUE TITLE
Unable to use DropNetRT w/o forking it and updating its references to the latest NuGet packages of Microsoft.Net.Http and Newtonsoft.Json.dll

### ISSUE THREAD

**Issue by danielkornev** [DropNet/DropNetRT#22]
We use these libraries in other parts of our product, and it seems that w/o forking DropNetRT and changing its NuGet references it is impossible to use DropNetRT in our project.

Is it an expected behavior?

```
System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. 
```

Here's an example of our error log:

```
DEBUG   2016-01-14 04:53:47Z EXCEPTION: System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ZU.Apps.Dropbox.DropboxApp.<TrySignIn>d__111.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at ZU.Apps.Dropbox.DropboxApp.TrySignIn(String userToken, String userSecret)
   at ZU.Apps.Dropbox.DropboxApp.TrySignInAsync() in C:\stuff\dev\zu_src\ZU\ZU.Core.Apps.Dropbox\DropboxApp.Internal.cs:line 420
   at ZU.Apps.Dropbox.AppPane.dropboxApp_Loaded(Object sender, RoutedEventArgs e) in C:\stuff\dev\zu_src\ZU\ZU.Core.Apps.Dropbox\AppPane.xaml.cs:line 177
   at ZU.Apps.Dropbox.DropboxApp.Initialize(IAppSettings settings, ISystemInformationModel sim, IAppManager appManager) in C:\stuff\dev\zu_src\ZU\ZU.Core.Apps.Dropbox\DropboxApp.cs:line 555
   at ZU.Apps.Dropbox.DropboxApp.OnConnection(ConnectMode mode) in C:\stuff\dev\zu_src\ZU\ZU.Core.Apps.Dropbox\DropboxApp.ZetApp.cs:line 48
   at SAL.Flatbed.PluginStorage.InitializePlugins()

=== Pre-bind state information ===
LOG: DisplayName = System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/stuff/dev/zu_src/Drops/Latest/
LOG: Initial PrivatePath = NULL
Calling assembly : DropNetRT, Version=1.5.20.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\stuff\dev\zu_src\Drops\Latest\ZetUniverse.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/stuff/dev/zu_src/Drops/Latest/System.Net.Http.Primitives.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

**Comment by dkarzon** [comment]
This is fixed by #23 and nuget package `v1.5.23` https://www.nuget.org/packages/DropNetRT/1.5.23
